;hostname    = 89.104.68.191
;username    = logs_user
;password    = lLxeTturtDkQ6cPp848dndFC
;database    = logs_db
;server_port = 8400
hostname     = 127.0.0.1
username     = root
password     = root
database     = pears_logs
auto_reconnect = true
multi_statements = false
