;hostname    = 54.37.139.10
;username    = server_user
;password    = ou0nnUOq3y74YEjcfI0zQN9F
;database    = server_db
;server_port = 8796
hostname     = 127.0.0.1
username     = root
password     = root
database     = pears
auto_reconnect = true
multi_statements = true