
#define COLOR_LIGHTGREEN_TEXT "{ABEA8F}"

#define COLOR_GREEN_TEXT "{00cc00}"

#define COLOR_LIGHTBLUE_TEXT "{33ccff}"
#define COLOR_BLUE 0x0088FFFF
#define COLOR_BLUE_TEXT "{0088ff}"
#define COLOR_AZURE 0x87CEFAFF
#define COLOR_AZURE_TEXT "{87cefa}"
#define COLOR_ORANGE 0xFF9000FF
#define COLOR_ORANGE_TEXT "{ff9000}"

#define COLOR_LIGHTRED_TEXT "{cd5700}"
#define COLOR_LIGHTYELLOW 0xFFCC66FF
#define COLOR_LIGHTYELLOW_TEXT "{FFCC66}"

#define COLOR_WHITE_TEXT "{f8f8ff}"

#define COLOR_PURPLE_TEXT "{8a2be2}"

#define COLOR_PINK_TEXT "{bb11bb}"
#define COLOR_ME 0xC2A2DAAA
#define COLOR_ME_TEXT "{c2a2da}"

#define COLOR_DARK_TEXT "{333333}"
#define COLOR_LIGHTDARK 0x606060FF
#define COLOR_LIGHTDARK_TEXT "{606060}"

#define COLOR_RED_TEXT "{dd0000}"
#define COLOR_GRAY 0xCBCBCBFF
#define COLOR_GRAY_TEXT "{cbcbcb}"
#define COLOR_PALEORANGE 0xD9C698FF
#define COLOR_PALEORANGE_TEXT "{d9c698}"