enum e_DialogId {
    NO_DIALOG_HANDLER = 1700,

    // Судебная система
    COURT_DIALOG_OFFERS = 3000, // Список заявок в суд
    COURT_DIALOG_OFFER_DONE_INFO, // Информация о выполненной заявке
    COURT_DIALOG_OFFER_WAITING_INFO, // Информация о заявке, ожидающей рассмотрения
    COURT_DIALOG_OFFER_CALL, // Информация о том, что судья вызвал вас на заседание
    COURT_DIALOG_OFFER_REVIEW, // Доступные варианты выбора для рассмотрения дела
    COURT_DIALOG_PROCESS_ACCEPT, // Принять выбранный вариант для рассмотрения дела
    COURT_DIALOG_ENTER_DEPOSIT, // Указание залога для вызволения / суммы для отработки
    COURT_DIALOG_CANCEL_OFFER, // Отмена заявки для подсудимого

    // Сдаться властям
    POLICE_DIALOG_SELF_SURRENDER,

    // Подфракции
    DIVISION_MENU,
    DIVISION_SETTINGS,
    DIVISION_SETNAME,
    DIVISION_ABBREVIATION,
    DIVISION_RANK_AMOUNT,
    DIVISION_RANK_SETNAME,
    DIVISION_RANK_SETNAME_SAVE,
    DIVISION_SPAWN,
    DIVISION_SETCOLOR,
    //DIVISION_SETVEHCOLOR,
    DIVISION_LEAVE,
    DIVISION_MEMBERS,
    DIVISION_INVITE,
    DIVISION_INVITE_SAVE,
    DIVISION_UNINVITE_SAVE,
    DIVISION_MEMBERS_LIST,
    DIVISION_ORDER_WEAPONS,

    // Организации
    ORGANIZATION_AVAILABLE_WEAPONS,

    // Установка доступных оружий для сотрудников департамента 
    ADMIN_SET_DEPARTWEAPONS_FRACTIONS, // Список фракций
    ADMIN_SET_DEPARTWEAPONS_LIST, // Список оружия

    // Система радаров
    RADAR_DIALOG_LIST, // Список радаров
    RADAR_DIALOG_MANAGEMENT, // Управление радаром
    RADAR_DIALOG_STATS,
    RADAR_DIALOG_SET_MAXSPEED,
    RADAR_DIALOG_SET_FINE,
    RADAR_DIALOG_PLACE,
    RADAR_DIALOG_DELETE,
    RADAR_DIALOG_REPAIR,

    // Тренировочные маршруты
    OBSTACLE_DIALOG_MENU,
    OBSTACLE_DIALOG_CREATE,
    OBSTACLE_DIALOG_SETNAME,
    OBSTACLE_DIALOG_SETTYPE,
    OBSTACLE_DIALOG_SETPASSTIME,
    OBSTACLE_DIALOG_SETPOINTS,
    OBSTACLE_DIALOG_SETVEHICLETYPE,
    OBSTACLE_DIALOG_START,
    OBSTACLE_DIALOG_START_MEMBERS,
    OBSTACLE_DIALOG_START_ADDMEMBER,
    OBSTACLE_DIALOG_CREATE_ACCEPT,
    OBSTACLE_DIALOG_END_ACCEPT,
    OBSTACLE_DIALOG_DELETE_ACCEPT,
    OBSTACLE_DIALOG_START_ACCEPT,
    OBSTACLE_DIALOG_CANCEL_CREATE_ACCEPT,
    OBSTACLE_DIALOG_STATS,

    // Оскорбления
    OFFENSE_DIALOG_MAIN,
    OFFENSE_DIALOG_REVIEW,
    OFFENSE_DIALOG_REVIEW_VERDICT,

    // Хэнк (Чёрный рынок)
    HANK_DIALOG_MAIN,
    HANK_DIALOG_ABOUT_ME,
    HANK_DIALOG_GOODS,
    HANK_DIALOG_BUY,

    // Заброшенная шахта (Зомби)
    MINEWAR_DIALOG_MAIN,
    MINEWAR_DIALOG_ABOUT,
    MINEWAR_DIALOG_TEAM,
    MINEWAR_DIALOG_ADDMEMBER,
    MINEWAR_START_ACCEPT,
    MINEWAR_DIALOG_INVITE
};