enum e_DialogId {
    NO_DIALOG_HANDLER = 1700,

    // Судебная система
    COURT_DIALOG_OFFERS = 3000, // Список заявок в суд
    COURT_DIALOG_OFFER_DONE_INFO, // Информация о выполненной заявке
    COURT_DIALOG_OFFER_WAITING_INFO, // Информация о заявке, ожидающей рассмотрения
    COURT_DIALOG_OFFER_CALL, // Информация о том, что судья вызвал вас на заседание
    COURT_DIALOG_OFFER_REVIEW, // Доступные варианты выбора для рассмотрения дела
    COURT_DIALOG_PROCESS_ACCEPT, // Принять выбранный вариант для рассмотрения дела
    COURT_DIALOG_ENTER_DEPOSIT, // Указание залога для вызволения / суммы для отработки
    COURT_DIALOG_CANCEL_OFFER, // Отмена заявки для подсудимого

    // Сдаться властям
    POLICE_DIALOG_SELF_SURRENDER,

    // Подфракции
    DIVISION_MENU,
    DIVISION_SETTINGS,
    DIVISION_SETNAME,
    DIVISION_ABBREVIATION,
    DIVISION_RANK_AMOUNT,
    DIVISION_RANK_SETNAME,
    DIVISION_RANK_SETNAME_SAVE,
    DIVISION_SPAWN,
    DIVISION_SETCOLOR,
    //DIVISION_SETVEHCOLOR,
    DIVISION_LEAVE,
    DIVISION_MEMBERS,
    DIVISION_INVITE,
    DIVISION_INVITE_SAVE,
    DIVISION_UNINVITE_SAVE,
    DIVISION_MEMBERS_LIST,
    DIVISION_ORDER_WEAPONS,

    // Организации
    ORGANIZATION_AVAILABLE_WEAPONS,

    // Установка доступных оружий для сотрудников департамента 
    ADMIN_SET_DEPARTWEAPONS_FRACTIONS, // Список фракций
    ADMIN_SET_DEPARTWEAPONS_LIST, // Список оружия

    // Система радаров
    RADAR_DIALOG_LIST, // Список радаров
    RADAR_DIALOG_MANAGEMENT, // Управление радаром
    RADAR_DIALOG_STATS,
    RADAR_DIALOG_SET_MAXSPEED,
    RADAR_DIALOG_SET_FINE,
    RADAR_DIALOG_PLACE,
    RADAR_DIALOG_DELETE,
    RADAR_DIALOG_REPAIR,

    // Тренировочные маршруты
    OBSTACLE_DIALOG_MENU,
    OBSTACLE_DIALOG_CREATE,
    OBSTACLE_DIALOG_SETNAME,
    OBSTACLE_DIALOG_SETTYPE,
    OBSTACLE_DIALOG_SETPASSTIME,
    OBSTACLE_DIALOG_SETPOINTS,
    OBSTACLE_DIALOG_SETVEHICLETYPE,
    OBSTACLE_DIALOG_START,
    OBSTACLE_DIALOG_START_MEMBERS,
    OBSTACLE_DIALOG_START_ADDMEMBER,
    OBSTACLE_DIALOG_CREATE_ACCEPT,
    OBSTACLE_DIALOG_END_ACCEPT,
    OBSTACLE_DIALOG_DELETE_ACCEPT,
    OBSTACLE_DIALOG_START_ACCEPT,
    OBSTACLE_DIALOG_CANCEL_CREATE_ACCEPT,
    OBSTACLE_DIALOG_STATS,

    // Оскорбления
    OFFENSE_DIALOG_MAIN,
    OFFENSE_DIALOG_REVIEW,
    OFFENSE_DIALOG_REVIEW_VERDICT,

    // Хэнк (Чёрный рынок)
    HANK_DIALOG_MAIN,
    HANK_DIALOG_ABOUT_ME,
    HANK_DIALOG_GOODS,
    HANK_DIALOG_SERVICES,
    HANK_DIALOG_BUY,
    HANK_DIALOG_BUY_SERVICE,
    HANK_DIALOG_DATABASE_ACTIVES,
    HANK_DIALOG_DATABASE_ACTIVES_ABOUT,
    HANK_DIALOG_DATABASE_ACTIVES_SELECT,
    HANK_DIALOG_DATABASE_ACTIVES_BUY,
    HANK_DIALOG_DATABASE_ACTIVES_REFUND,

    // Заброшенная шахта (Зомби)
    MINEWAR_DIALOG_MAIN,
    MINEWAR_DIALOG_ABOUT,
    MINEWAR_DIALOG_TEAM,
    MINEWAR_DIALOG_ADDMEMBER,
    MINEWAR_START_ACCEPT,
    MINEWAR_DIALOG_INVITE,
    MINEWAR_DIALOG_EXIT,
    MINEWAR_DIALOG_QUEST,

    // Гробница фараона (Мумии)
    TOMB_DIALOG_MAIN,
    TOMB_DIALOG_ABOUT,
    TOMB_DIALOG_TEAM,
    TOMB_DIALOG_ADDMEMBER,
    TOMB_START_ACCEPT,
    TOMB_DIALOG_INVITE,
    TOMB_DIALOG_EXIT,
    TOMB_DIALOG_QUEST,
    
    // Радиоперехватчик
    RADIO_INTERCEPTOR_MAIN,
    RADIO_INTERCEPTOR_FIND,
    RADIO_INTERCEPTOR_SETSTATES,

    // Взлом базы данных
    POLICE_DATABASE_DIALOG_HACK,
    POLICE_DATABASE_DIALOG_VENT_EXIT,
    POLICE_DATABASE_DIALOG_CLEAR_MENU,
    POLICE_DATABASE_DIALOG_CLEAR_ID,
    POLICE_DATABASE_DIALOG_HACK_START,
    POLICE_DATABASE_DIALOG_HACKPASS_START,
    POLICE_DATABASE_DIALOG_HACKPASS,
    POLICE_DATABASE_DIALOG_HACKPASS_DECLINE,

    // Катана Дуэль
    KATANA_DUEL_MENU,
    KATANA_DUEL_PRICE,
    KATANA_DUEL_CONFIRM,
    KATANA_DUEL_QUEST,

    // CNN
    CNN_DIALOG_SEND_AD,
    CNN_DIALOG_CHOOSE_TYPE,
    CNN_DIALOG_EDITLIST_AD,
    CNN_DIALOG_EDIT_AD,
    CNN_DIALOG_EDIT_INPUT_AD,
    CNN_DIALOG_CANCEL_INPUT_AD,
    CNN_DIALOG_CHECK_AD,
    CNN_DIALOG_EDIT_PRICE_SELECT,
    CNN_DIALOG_EDIT_PRICE_ENTER,
    CNN_DIALOG_LIST_AD,
    CNN_DIALOG_AGETAVIA,

    // Квартиры
    APARTMENTS_DIALOG_ELIVATOR,
    APARTMENTS_DIALOG_ENTER,
    APARTMENTS_DIALOG_BUY,
    APARTMENTS_DIALOG_TABLEPUT,
    APARTMENTS_DIALOG_TABLETAKE,
    APARTMENTS_DIALOG_MENU,
    APARTMENTS_DIALOG_MYROOMS,
    APARTMENTS_DIALOG_SELLROOM,
    APARTMENTS_DIALOG_SELLROOMGOS,
    APARTMENTS_DIALOG_ROOMINFO,
    APARTMENTS_DIALOG_GPS,
    APARTMENTS_DIALOG_SPAWNCHOICE,

    // Холодильники
    FRIDGE_DIALOG_PUT,
    FRIDGE_DIALOG_TAKE,

    // Электростанции
    ELECTRICIAN_DIALOG_PAYMENTHOUSE,
    ELECTRICIAN_DIALOG_PAYMENTTERMINAL,
    ELECTRICIAN_DIALOG_GOJOB,
    ELECTRICIAN_DIALOG_HELP,
    ELECTRICIAN_DIALOG_AGETCAR,
    ELECTRICIAN_DIALOG_HOUSELIST,
    ELECTRICIAN_DIALOG_HOUSESELECTCONNECT,
    ELECTRICIAN_DIALOG_TICKETLIST,
    ELECTRICIAN_DIALOG_TICKETLISTHOUSE,
    ELECTRICIAN_DIALOG_TICKETLISTTERM,

    // Семья
    FAMILY_DIALOG_ADDVEHICLE,
    FAMILY_DIALOG_PLATE,

    // GPS
    GPS_DIALOG_WAREHOUSE,

    // Раскопка могил
    GRAVES_DIALOG_MAIN,
    GRAVES_DIALOG_OPEN,
    GRAVES_DIALOG_BIOGRAPHY,
    GRAVES_DIALOG_LOOT,

    // Lobby
    LOBBY_LIST,
    LOBBY_INVITE,
    LOBBY_ACCEPTINVITE,
    LOBBY_UNINVITE,
    LOBBY_ACCEPTHALLOWEEN,

    //AUTOSERVICE
    AUTOSERVICE_BACKDETAIL,

    // Casino
    CASINO_EDITCHIPSPROCENT,

    // Станок для артов
    ACCESSORYCRAFT_LIST_TYPE,
    ACCESSORYCRAFT_LIST,
    ACCESSORYCRAFT_INFORMATION,
    SKINCRAFT_LIST_TYPE,
    SKINCRAFT_LIST,
    CRAFT_LIST,
    CRAFT_CONSUMABLES_LIST,
    
    // Заправка транспорта
    FILLKANI_DIALOG_ENTER,

    // Дом
    DOM_DIALOG_DONATE,
    DOM_DIALOG_DONATE_BUY,

    // Администрация
    ADMIN_DIALOG_CHECKEVENTS,
    ADMIN_DIALOG_CHECKEVENTS_STATS,

    // Купонные шкатулки
    COUPON_DIALOG_INFORMATION,

    // МП
    MP_DIALOG_TIME_INPUT,
    MP_DIALOG_SKIN_SELECT,
    MP_DIALOG_SKIN_INPUT,

    
    // Боевой пропуск
    BATTLEPASS_SHOW_MENU,
    BATTLEPASS_SHOW_MENU_TASKS,
    BATTLEPASS_SHOW_MENU_AWARDS,
    BATTLEPASS_SHOW_MENU_TASKINFO,
    BATTLEPASS_SHOW_LEVELMENU,
    BATTLEPASS_SHOW_LEVELMENU_INFO,

    // Питомцы
    PETS_SHOW_LIST,
    PETS_SHOW_PETMANAGE,
    PETS_SHOW_PETMANAGE_TASK,
    PETS_SHOW_PETMANAGE_INFORMATION,
    PET_CREATETASK_ATTAC,
    PET_CREATETASK_SNIFF,
    PETS_HELP,
    PETS_HELP_LIST,
    PETS_HELP_LIST_FEATURES,
    PETS_HELP_FEATURES,
    PETS_SHOW_PETMANAGE_POWER,
    PETS_SHOW_PETMANAGE_AGILITY,
    PETS_SHOW_PETMANAGE_ENDURENCE,

    // Новый год
    NEWYEAR_SHOW_STARTQUEST,

    // Тюремный терминал
    JAIL_DIALOG_TERMINAL,

    // Архив Интерьеров
    PACK_INTERIORS_MENU,
    PACK_INTERIORS_SETTING,
    PACK_INTERIORS_INSTALL,
    PACK_INTERIORS_SAVE,
    PACK_INTERIORS_DELETE,
    PACK_INTERIORS_NAME,
    PACK_INTERIORS_INFO,
    PACK_INTERIORS_DONATE,

    // Клонируем объект в интерьере дома или биза
    CLONE_OBJECT_INTERIOR
};

